# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
!pip install numpy


In [7]:
import numpy as np
import random 

In [16]:

list=np.random.randint(1,20,size=(5,5))
list

array([[11,  5, 11,  9, 13],
       [ 8,  2, 12, 12, 12],
       [18,  1, 19,  1,  3],
       [ 9, 19, 17, 14,  7],
       [ 1, 18,  8,  4,  5]])

In [23]:
list[:,2]=1
list

array([[11,  5,  1,  9, 13],
       [ 8,  2,  1, 12, 12],
       [18,  1,  1,  1,  3],
       [ 9, 19,  1, 14,  7],
       [ 1, 18,  1,  4,  5]])

In [24]:
#Ass-2
list2=np.random.randint(1,36,size=(6,6))
list2

array([[33,  4,  8, 17,  1, 13],
       [ 8, 30, 30, 27, 29, 33],
       [16, 23,  2, 12, 30,  4],
       [12,  6,  4,  8, 32,  3],
       [20, 19, 14,  2, 19, 15],
       [14, 27,  5, 11,  6, 16]])

In [25]:
list2[2:5,1:4]

array([[23,  2, 12],
       [ 6,  4,  8],
       [19, 14,  2]])

In [34]:
print(list[0:1,:])
print(list[1:,0:1],end="       ")
print(list[1:4,4:5],end="      ")
print(list[4:,1:])

[[11  5  1  9 13]]
[[ 8]
 [18]
 [ 9]
 [ 1]]       [[12]
 [ 3]
 [ 7]]      [[18  1  4  5]]


In [36]:
t=np.random.randint(1,20,size=(3,4))
print(t)
s=np.random.randint(1,20,size=(3,4))
print(s)
print(s+t)

[[ 5 13 15  3]
 [12 18 16  9]
 [11 11 18  1]]
[[10  7  6  2]
 [19 19 13 11]
 [17 14  8 18]]
[[15 20 21  5]
 [31 37 29 20]
 [28 25 26 19]]


In [38]:
n=np.random.randint(1,20,size=(4,4))
print(n)
row_sum=np.sum(n,axis=1)
col_sum=np.sum(n,axis=0)
print(row_sum)
print(col_sum)

[[14  8 14 18]
 [16  7 13 13]
 [ 6 16  2  8]
 [18  4 15 12]]
[54 49 32 49]
[54 35 44 51]


In [45]:
#ass4
arr=np.random.randint(1,20,size=(5,5))
print(arr.mean())
print(arr.var())
print(arr.std())
print(np.median(arr))

10.12
34.9856
5.91486263576763
9.0


In [54]:
def ran(x,y):
    arr=np.random.randint(1,20,size=(x,y))
    return arr



In [63]:
to=ran(3,3)
print(to)
ad=[1,2,3]
too=to-ad
print(too)

[[15 16 18]
 [12  6 18]
 [19  9 11]]
[[14 14 15]
 [11  4 15]
 [18  7  8]]


In [64]:
linear=ran(3,3)
print(linear)

[[ 4 19  8]
 [14 16 13]
 [15 17  5]]


In [66]:
print(np.linalg.det(linear))
print(np.linalg.eigvals(linear))

1794.9999999999998
[37.92787197+0.j         -6.46393599+2.35461349j -6.46393599-2.35461349j]


In [67]:
s=np.random.randint(1,9,size=(3,3))
print(s)

[[6 8 8]
 [5 2 6]
 [6 8 4]]


In [68]:
re_s=s.reshape(1,9)
re_s

array([[6, 8, 8, 5, 2, 6, 6, 8, 4]])

In [69]:
re_re_s=re_s.reshape(9,1)
re_re_s

array([[6],
       [8],
       [8],
       [5],
       [2],
       [6],
       [6],
       [8],
       [4]])

In [70]:
t=re_re_s.reshape(3,3)
t

array([[6, 8, 8],
       [5, 2, 6],
       [6, 8, 4]])

In [80]:
data=[['name', 'age', 'weight'],
       ['a', 2, 60.3],
       ['b', 8, 40.3]]
print(data)

[['name', 'age', 'weight'], ['a', 2, 60.3], ['b', 8, 40.3]]


In [81]:
np.sort(data[1:],axis=1)

array([['2', '60.3', 'a'],
       ['40.3', '8', 'b']], dtype='<U32')

In [84]:
m=ran(4,4)
print(m)

[[13 13 13 11]
 [13 14 10 18]
 [ 6  5  2 10]
 [ 8 18 15  9]]


In [86]:
masked=m<10
print(m[masked].sum())


30
